name: dummy-ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  dummy:
    name: Dummy
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: exit 0
