name: Long CI for README

on:
  push:
    branches:
      - main
    tags-ignore:
      - *
    paths:
      - README.adoc
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths:
      - README.adoc


concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('long-ci-readme-{0}', github.sha) || format('demo-agp7-ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  long-ci:
    name: Long CI
    runs-on: ubuntu-latest
    steps:
      - name: wait
        run: sleep 20
      - name: fail
        run: exit 1
