name: Long CI for README

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - README.adoc
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths:
      - README.adoc

jobs:
  long-ci:
    name: Long CI
    runs-on: ubuntu-latest
    steps:
      - name: wait
        run: sleep 20
      - name: fail
        run: exit 1
