name: Wait for checks

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('wait-for-checks-{0}', github.sha) || format('demo-agp7-ci-{0}', github.ref) }}
  cancel-in-progress: true


jobs:
  enforce-all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
