name: Wait for checks

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  enforce-all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
